//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.08 at 10:00:48 AM EDT
//


package com.galenrhodes.gnustep.options.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClangTargetsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ClangTargetsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="x86_64" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="arm32" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="arm64" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClangTargetsType", propOrder = {
        "x8664", "arm32", "arm64"
})
public class ClangTargetsType {

    @XmlElement(name = "x86_64", defaultValue = "true")
    protected Boolean x8664;
    @XmlElement(defaultValue = "false")
    protected Boolean arm32;
    @XmlElement(defaultValue = "false")
    protected Boolean arm64;

    /**
     * Gets the value of the arm32 property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isArm32() {
        return arm32;
    }

    /**
     * Gets the value of the arm64 property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isArm64() {
        return arm64;
    }

    /**
     * Gets the value of the x8664 property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isX8664() {
        return x8664;
    }

    /**
     * Sets the value of the arm32 property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setArm32(Boolean value) {
        this.arm32 = value;
    }

    /**
     * Sets the value of the arm64 property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setArm64(Boolean value) {
        this.arm64 = value;
    }

    /**
     * Sets the value of the x8664 property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setX8664(Boolean value) {
        this.x8664 = value;
    }

}
