//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.05 at 12:54:41 PM EDT
//


package com.galenrhodes.gnustep.options.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListValuesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ListValuesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LibraryCombo" type="{http://www.projectgalen.com/gnustepbuilder}ValuesArrayType"/&gt;
 *         &lt;element name="Layout" type="{http://www.projectgalen.com/gnustepbuilder}ValuesArrayType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListValuesType", propOrder = {
        "libraryCombo", "layout"
})
public class ListValuesType {

    @XmlElement(name = "LibraryCombo", required = true)
    protected ValuesArrayType libraryCombo;
    @XmlElement(name = "Layout", required = true)
    protected ValuesArrayType layout;

    /**
     * Gets the value of the layout property.
     *
     * @return
     *     possible object is
     *     {@link ValuesArrayType }
     *
     */
    public ValuesArrayType getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     *
     * @param value
     *     allowed object is
     *     {@link ValuesArrayType }
     *
     */
    public void setLayout(ValuesArrayType value) {
        this.layout = value;
    }

    /**
     * Gets the value of the libraryCombo property.
     *
     * @return
     *     possible object is
     *     {@link ValuesArrayType }
     *
     */
    public ValuesArrayType getLibraryCombo() {
        return libraryCombo;
    }

    /**
     * Sets the value of the libraryCombo property.
     *
     * @param value
     *     allowed object is
     *     {@link ValuesArrayType }
     *
     */
    public void setLibraryCombo(ValuesArrayType value) {
        this.libraryCombo = value;
    }

}
