//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.04 at 01:41:58 PM EDT
//

package com.galenrhodes.gnustep.options.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ListValuesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ListValuesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LibraryCombo" type="{http://www.projectgalen.com/gnustepbuilder}ValuesArrayType"/>
 *         &lt;element name="Layout" type="{http://www.projectgalen.com/gnustepbuilder}ValuesArrayType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListValuesType", propOrder = {
        "libraryCombo", "layout"
})
public class ListValuesType {

    @XmlElement(name = "LibraryCombo", required = true)
    protected ValuesArrayType libraryCombo;
    @XmlElement(name = "Layout", required = true)
    protected ValuesArrayType layout;

    /**
     * Gets the value of the layout property.
     *
     * @return possible object is {@link ValuesArrayType }
     */
    public ValuesArrayType getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     *
     * @param value allowed object is {@link ValuesArrayType }
     */
    public void setLayout(ValuesArrayType value) {
        this.layout = value;
    }

    /**
     * Gets the value of the libraryCombo property.
     *
     * @return possible object is {@link ValuesArrayType }
     */
    public ValuesArrayType getLibraryCombo() {
        return libraryCombo;
    }

    /**
     * Sets the value of the libraryCombo property.
     *
     * @param value allowed object is {@link ValuesArrayType }
     */
    public void setLibraryCombo(ValuesArrayType value) {
        this.libraryCombo = value;
    }

}
