//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 10:44:00 AM EDT 
//


package com.galenrhodes.gnustep.builder.options.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileSystemLayoutsEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileSystemLayoutsEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="fhs"/&gt;
 *     &lt;enumeration value="fhs-system"/&gt;
 *     &lt;enumeration value="gnustep"/&gt;
 *     &lt;enumeration value="gnustep-with-network"/&gt;
 *     &lt;enumeration value="debian"/&gt;
 *     &lt;enumeration value="apple"/&gt;
 *     &lt;enumeration value="mac"/&gt;
 *     &lt;enumeration value="next"/&gt;
 *     &lt;enumeration value="standalone"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FileSystemLayoutsEnum", namespace = "http://www.projectgalen.com/gnustepbuilder")
@XmlEnum
public enum FileSystemLayoutsEnum {

    @XmlEnumValue("fhs")
    FHS("fhs"),
    @XmlEnumValue("fhs-system")
    FHS_SYSTEM("fhs-system"),
    @XmlEnumValue("gnustep")
    GNUSTEP("gnustep"),
    @XmlEnumValue("gnustep-with-network")
    GNUSTEP_WITH_NETWORK("gnustep-with-network"),
    @XmlEnumValue("debian")
    DEBIAN("debian"),
    @XmlEnumValue("apple")
    APPLE("apple"),
    @XmlEnumValue("mac")
    MAC("mac"),
    @XmlEnumValue("next")
    NEXT("next"),
    @XmlEnumValue("standalone")
    STANDALONE("standalone");
    private final String value;

    FileSystemLayoutsEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FileSystemLayoutsEnum fromValue(String v) {
        for (FileSystemLayoutsEnum c: FileSystemLayoutsEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
