//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.18 at 12:19:28 PM EDT
//


package com.galenrhodes.gnustep.builder.options.data;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for GNUstepOptions complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GNUstepOptions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="WorkingDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InstallDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InstallPrerequisiteSoftware" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="InstallLibkqueue" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="CreateEntriesIn_ld_so_conf_d" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="BuildClang" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ClangTargets" type="{http://www.projectgalen.com/gnustepbuilder}ClangTargetsType"/&gt;
 *         &lt;element name="BuildGoogleTest" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="UseSwiftLibDispatch" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="BuildLibDispatchFirst" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="OldABICompat" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="CustomLibName" type="{http://www.projectgalen.com/gnustepbuilder}CustomLibNameType"/&gt;
 *         &lt;element name="BuildMakeTwice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="NoMixedABI" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="NonFragileABI" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ObjectiveCArc" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DebugByDefault" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="NativeObjectiveCExceptions" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="RuntimeABI" type="{http://www.projectgalen.com/gnustepbuilder}RuntimeABIEnum"/&gt;
 *         &lt;element name="LibraryCombo" type="{http://www.projectgalen.com/gnustepbuilder}LibraryComboEnum"/&gt;
 *         &lt;element name="Layout" type="{http://www.projectgalen.com/gnustepbuilder}FileSystemLayoutsEnum"/&gt;
 *         &lt;element name="Modules" type="{http://www.projectgalen.com/gnustepbuilder}Modules"/&gt;
 *         &lt;element name="Prerequisits" type="{http://www.projectgalen.com/gnustepbuilder}Prerequisits"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GNUstepOptions", namespace = "http://www.projectgalen.com/gnustepbuilder", propOrder = {

})
public class GNUstepOptions {

    @XmlElement(name = "WorkingDirectory", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected String                workingDirectory;
    @XmlElement(name = "InstallDirectory", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected String                installDirectory;
    @XmlElement(name = "InstallPrerequisiteSoftware", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected boolean               installPrerequisiteSoftware;
    @XmlElement(name = "InstallLibkqueue", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected boolean               installLibkqueue;
    @XmlElement(name = "CreateEntriesIn_ld_so_conf_d", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected boolean               createEntriesInLdSoConfD;
    @XmlElement(name = "BuildClang", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected boolean               buildClang;
    @XmlElement(name = "ClangTargets", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected ClangTargetsType      clangTargets;
    @XmlElement(name = "BuildGoogleTest", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected boolean               buildGoogleTest;
    @XmlElement(name = "UseSwiftLibDispatch", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected boolean               useSwiftLibDispatch;
    @XmlElement(name = "BuildLibDispatchFirst", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected boolean               buildLibDispatchFirst;
    @XmlElement(name = "OldABICompat", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected boolean               oldABICompat;
    @XmlElement(name = "CustomLibName", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected CustomLibNameType     customLibName;
    @XmlElement(name = "BuildMakeTwice", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected boolean               buildMakeTwice;
    @XmlElement(name = "NoMixedABI", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected boolean               noMixedABI;
    @XmlElement(name = "NonFragileABI", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected boolean               nonFragileABI;
    @XmlElement(name = "ObjectiveCArc", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected boolean               objectiveCArc;
    @XmlElement(name = "DebugByDefault", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected boolean               debugByDefault;
    @XmlElement(name = "NativeObjectiveCExceptions", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected boolean               nativeObjectiveCExceptions;
    @XmlElement(name = "RuntimeABI", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true, defaultValue = "2.0")
    @XmlSchemaType(name = "string")
    protected RuntimeABIEnum        runtimeABI;
    @XmlElement(name = "LibraryCombo", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true, defaultValue = "ng-gnu-gnu")
    @XmlSchemaType(name = "string")
    protected LibraryComboEnum      libraryCombo;
    @XmlElement(name = "Layout", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true, defaultValue = "fhs")
    @XmlSchemaType(name = "string")
    protected FileSystemLayoutsEnum layout;
    @XmlElement(name = "Modules", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected Modules               modules;
    @XmlElement(name = "Prerequisits", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected Prerequisits          prerequisits;

    /**
     * Gets the value of the workingDirectory property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public synchronized String getWorkingDirectory() {
        return workingDirectory;
    }

    /**
     * Sets the value of the workingDirectory property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public synchronized void setWorkingDirectory(String value) {
        this.workingDirectory = value;
    }

    /**
     * Gets the value of the installDirectory property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public synchronized String getInstallDirectory() {
        return installDirectory;
    }

    /**
     * Sets the value of the installDirectory property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public synchronized void setInstallDirectory(String value) {
        this.installDirectory = value;
    }

    /**
     * Gets the value of the prerequisits property.
     *
     * @return
     *     possible object is
     *     {@link Prerequisits }
     *
     */
    public synchronized Prerequisits getPrerequisits() {
        return prerequisits;
    }

    /**
     * Sets the value of the prerequisits property.
     *
     * @param value
     *     allowed object is
     *     {@link Prerequisits }
     *
     */
    public synchronized void setPrerequisits(Prerequisits value) {
        this.prerequisits = value;
    }

    /**
     * Gets the value of the buildClang property.
     *
     */
    public synchronized boolean isBuildClang() {
        return buildClang;
    }

    /**
     * Sets the value of the buildClang property.
     *
     */
    public synchronized void setBuildClang(boolean value) {
        this.buildClang = value;
    }

    /**
     * Gets the value of the buildGoogleTest property.
     *
     */
    public synchronized boolean isBuildGoogleTest() {
        return buildGoogleTest;
    }

    /**
     * Sets the value of the buildGoogleTest property.
     *
     */
    public synchronized void setBuildGoogleTest(boolean value) {
        this.buildGoogleTest = value;
    }

    /**
     * Gets the value of the buildLibDispatchFirst property.
     *
     */
    public synchronized boolean isBuildLibDispatchFirst() {
        return buildLibDispatchFirst;
    }

    /**
     * Sets the value of the buildLibDispatchFirst property.
     *
     */
    public synchronized void setBuildLibDispatchFirst(boolean value) {
        this.buildLibDispatchFirst = value;
    }

    /**
     * Gets the value of the clangTargets property.
     *
     * @return
     *     possible object is
     *     {@link ClangTargetsType }
     *
     */
    public synchronized ClangTargetsType getClangTargets() {
        return clangTargets;
    }

    /**
     * Sets the value of the clangTargets property.
     *
     * @param value
     *     allowed object is
     *     {@link ClangTargetsType }
     *
     */
    public synchronized void setClangTargets(ClangTargetsType value) {
        this.clangTargets = value;
    }

    /**
     * Gets the value of the buildMakeTwice property.
     */
    public synchronized boolean isBuildMakeTwice() {
        return buildMakeTwice;
    }

    /**
     * Sets the value of the buildMakeTwice property.
     */
    public synchronized void setBuildMakeTwice(boolean value) {
        this.buildMakeTwice = value;
    }

    /**
     * Gets the value of the createEntriesInLdSoConfD property.
     */
    public synchronized boolean isCreateEntriesInLdSoConfD() {
        return createEntriesInLdSoConfD;
    }

    /**
     * Sets the value of the createEntriesInLdSoConfD property.
     */
    public synchronized void setCreateEntriesInLdSoConfD(boolean value) {
        this.createEntriesInLdSoConfD = value;
    }

    /**
     * Gets the value of the debugByDefault property.
     */
    public synchronized boolean isDebugByDefault() {
        return debugByDefault;
    }

    /**
     * Sets the value of the debugByDefault property.
     */
    public synchronized void setDebugByDefault(boolean value) {
        this.debugByDefault = value;
    }

    /**
     * Gets the value of the installLibkqueue property.
     */
    public synchronized boolean isInstallLibkqueue() {
        return installLibkqueue;
    }

    /**
     * Sets the value of the installLibkqueue property.
     *
     */
    public synchronized void setInstallLibkqueue(boolean value) {
        this.installLibkqueue = value;
    }

    /**
     * Gets the value of the customLibName property.
     *
     * @return
     *     possible object is
     *     {@link CustomLibNameType }
     *
     */
    public synchronized CustomLibNameType getCustomLibName() {
        return customLibName;
    }

    /**
     * Sets the value of the customLibName property.
     *
     * @param value
     *     allowed object is
     *     {@link CustomLibNameType }
     *
     */
    public synchronized void setCustomLibName(CustomLibNameType value) {
        this.customLibName = value;
    }

    /**
     * Gets the value of the installPrerequisiteSoftware property.
     *
     */
    public synchronized boolean isInstallPrerequisiteSoftware() {
        return installPrerequisiteSoftware;
    }

    /**
     * Sets the value of the installPrerequisiteSoftware property.
     */
    public synchronized void setInstallPrerequisiteSoftware(boolean value) {
        this.installPrerequisiteSoftware = value;
    }

    /**
     * Gets the value of the nativeObjectiveCExceptions property.
     *
     */
    public synchronized boolean isNativeObjectiveCExceptions() {
        return nativeObjectiveCExceptions;
    }

    /**
     * Sets the value of the nativeObjectiveCExceptions property.
     */
    public synchronized void setNativeObjectiveCExceptions(boolean value) {
        this.nativeObjectiveCExceptions = value;
    }

    /**
     * Gets the value of the noMixedABI property.
     *
     */
    public synchronized boolean isNoMixedABI() {
        return noMixedABI;
    }

    /**
     * Sets the value of the noMixedABI property.
     *
     */
    public synchronized void setNoMixedABI(boolean value) {
        this.noMixedABI = value;
    }

    /**
     * Gets the value of the nonFragileABI property.
     *
     */
    public synchronized boolean isNonFragileABI() {
        return nonFragileABI;
    }

    /**
     * Sets the value of the nonFragileABI property.
     *
     */
    public synchronized void setNonFragileABI(boolean value) {
        this.nonFragileABI = value;
    }

    /**
     * Gets the value of the objectiveCArc property.
     *
     */
    public synchronized boolean isObjectiveCArc() {
        return objectiveCArc;
    }

    /**
     * Sets the value of the objectiveCArc property.
     *
     */
    public synchronized void setObjectiveCArc(boolean value) {
        this.objectiveCArc = value;
    }

    /**
     * Gets the value of the oldABICompat property.
     *
     */
    public synchronized boolean isOldABICompat() {
        return oldABICompat;
    }

    /**
     * Sets the value of the oldABICompat property.
     *
     */
    public synchronized void setOldABICompat(boolean value) {
        this.oldABICompat = value;
    }

    /**
     * Gets the value of the runtimeABI property.
     *
     * @return
     *     possible object is
     *     {@link RuntimeABIEnum }
     *
     */
    public synchronized RuntimeABIEnum getRuntimeABI() {
        return runtimeABI;
    }

    /**
     * Sets the value of the runtimeABI property.
     *
     * @param value
     *     allowed object is
     *     {@link RuntimeABIEnum }
     *
     */
    public synchronized void setRuntimeABI(RuntimeABIEnum value) {
        this.runtimeABI = value;
    }

    /**
     * Gets the value of the libraryCombo property.
     *
     * @return
     *     possible object is
     *     {@link LibraryComboEnum }
     *
     */
    public synchronized LibraryComboEnum getLibraryCombo() {
        return libraryCombo;
    }

    /**
     * Sets the value of the libraryCombo property.
     *
     * @param value
     *     allowed object is
     *     {@link LibraryComboEnum }
     *
     */
    public synchronized void setLibraryCombo(LibraryComboEnum value) {
        this.libraryCombo = value;
    }

    /**
     * Gets the value of the layout property.
     *
     * @return
     *     possible object is
     *     {@link FileSystemLayoutsEnum }
     *
     */
    public synchronized FileSystemLayoutsEnum getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     *
     * @param value
     *     allowed object is
     *     {@link FileSystemLayoutsEnum }
     *
     */
    public synchronized void setLayout(FileSystemLayoutsEnum value) {
        this.layout = value;
    }

    /**
     * Gets the value of the modules property.
     *
     * @return
     *     possible object is
     *     {@link Modules }
     *
     */
    public synchronized Modules getModules() {
        return modules;
    }

    /**
     * Sets the value of the modules property.
     *
     * @param value
     *     allowed object is
     *     {@link Modules }
     *
     */
    public synchronized void setModules(Modules value) {
        this.modules = value;
    }

    /**
     * Gets the value of the useSwiftLibDispatch property.
     *
     */
    public synchronized boolean isUseSwiftLibDispatch() {
        return useSwiftLibDispatch;
    }

    /**
     * Sets the value of the useSwiftLibDispatch property.
     */
    public synchronized void setUseSwiftLibDispatch(boolean value) {
        this.useSwiftLibDispatch = value;
    }

}
