//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.17 at 10:44:00 AM EDT
//


package com.galenrhodes.gnustep.builder.options.data;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for GNUstepOptions complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GNUstepOptions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WorkingDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InstallDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InstallPrerequisiteSoftware" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="InstallLibkqueue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CreateEntriesIn_ld_so_conf_d" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="BuildClang" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ClangTargets" type="{http://www.projectgalen.com/gnustepbuilder}ClangTargetsType"/&gt;
 *         &lt;element name="BuildGoogleTest" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="UseSwiftLibDispatch" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="BuildLibDispatchFirst" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OldABICompat" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CustomLibName" type="{http://www.projectgalen.com/gnustepbuilder}CustomLibNameType" minOccurs="0"/&gt;
 *         &lt;element name="BuildMakeTwice" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="NoMixedABI" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="NonFragileABI" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ObjectiveCArc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="DebugByDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="NativeObjectiveCExceptions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="RuntimeABI" type="{http://www.projectgalen.com/gnustepbuilder}RuntimeABIEnum"/&gt;
 *         &lt;element name="LibraryCombo" type="{http://www.projectgalen.com/gnustepbuilder}LibraryComboEnum"/&gt;
 *         &lt;element name="Layout" type="{http://www.projectgalen.com/gnustepbuilder}FileSystemLayoutsEnum"/&gt;
 *         &lt;element name="SourceLocations" type="{http://www.projectgalen.com/gnustepbuilder}SourceLocation" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GNUstepOptions", namespace = "http://www.projectgalen.com/gnustepbuilder", propOrder = {
    "workingDirectory",
    "installDirectory",
    "installPrerequisiteSoftware",
    "installLibkqueue",
    "createEntriesInLdSoConfD",
    "buildClang",
    "clangTargets",
    "buildGoogleTest",
    "useSwiftLibDispatch",
    "buildLibDispatchFirst",
    "oldABICompat",
    "customLibName",
    "buildMakeTwice",
    "noMixedABI",
    "nonFragileABI",
    "objectiveCArc",
    "debugByDefault",
    "nativeObjectiveCExceptions",
    "runtimeABI",
    "libraryCombo",
    "layout",
    "sourceLocations"
})
public class GNUstepOptions {

    @XmlElement(name = "WorkingDirectory", namespace = "http://www.projectgalen.com/gnustepbuilder")
    protected String workingDirectory;
    @XmlElement(name = "InstallDirectory", namespace = "http://www.projectgalen.com/gnustepbuilder")
    protected String installDirectory;
    @XmlElement(name = "InstallPrerequisiteSoftware", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected Boolean installPrerequisiteSoftware;
    @XmlElement(name = "InstallLibkqueue", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected Boolean installLibkqueue;
    @XmlElement(name = "CreateEntriesIn_ld_so_conf_d", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected Boolean createEntriesInLdSoConfD;
    @XmlElement(name = "BuildClang", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected Boolean buildClang;
    @XmlElement(name = "ClangTargets", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected ClangTargetsType clangTargets;
    @XmlElement(name = "BuildGoogleTest", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected Boolean buildGoogleTest;
    @XmlElement(name = "UseSwiftLibDispatch", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected Boolean useSwiftLibDispatch;
    @XmlElement(name = "BuildLibDispatchFirst", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected Boolean buildLibDispatchFirst;
    @XmlElement(name = "OldABICompat", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected Boolean oldABICompat;
    @XmlElement(name = "CustomLibName", namespace = "http://www.projectgalen.com/gnustepbuilder")
    protected CustomLibNameType customLibName;
    @XmlElement(name = "BuildMakeTwice", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "false")
    protected Boolean buildMakeTwice;
    @XmlElement(name = "NoMixedABI", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected Boolean noMixedABI;
    @XmlElement(name = "NonFragileABI", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected Boolean nonFragileABI;
    @XmlElement(name = "ObjectiveCArc", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected Boolean objectiveCArc;
    @XmlElement(name = "DebugByDefault", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected Boolean debugByDefault;
    @XmlElement(name = "NativeObjectiveCExceptions", namespace = "http://www.projectgalen.com/gnustepbuilder", defaultValue = "true")
    protected Boolean nativeObjectiveCExceptions;
    @XmlElement(name = "RuntimeABI", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true, defaultValue = "2.0")
    @XmlSchemaType(name = "string")
    protected RuntimeABIEnum runtimeABI;
    @XmlElement(name = "LibraryCombo", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true, defaultValue = "ng-gnu-gnu")
    @XmlSchemaType(name = "string")
    protected LibraryComboEnum libraryCombo;
    @XmlElement(name = "Layout", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true, defaultValue = "fhs")
    @XmlSchemaType(name = "string")
    protected FileSystemLayoutsEnum layout;
    @XmlElement(name = "SourceLocations", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected List<SourceLocation> sourceLocations;

    /**
     * Gets the value of the workingDirectory property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public synchronized String getWorkingDirectory() {
        return workingDirectory;
    }

    /**
     * Sets the value of the workingDirectory property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public synchronized void setWorkingDirectory(String value) {
        this.workingDirectory = value;
    }

    /**
     * Gets the value of the installDirectory property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public synchronized String getInstallDirectory() {
        return installDirectory;
    }

    /**
     * Sets the value of the installDirectory property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public synchronized void setInstallDirectory(String value) {
        this.installDirectory = value;
    }

    /**
     * Gets the value of the installPrerequisiteSoftware property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isInstallPrerequisiteSoftware() {
        return installPrerequisiteSoftware;
    }

    /**
     * Sets the value of the installPrerequisiteSoftware property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setInstallPrerequisiteSoftware(Boolean value) {
        this.installPrerequisiteSoftware = value;
    }

    /**
     * Gets the value of the installLibkqueue property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isInstallLibkqueue() {
        return installLibkqueue;
    }

    /**
     * Sets the value of the installLibkqueue property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setInstallLibkqueue(Boolean value) {
        this.installLibkqueue = value;
    }

    /**
     * Gets the value of the createEntriesInLdSoConfD property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isCreateEntriesInLdSoConfD() {
        return createEntriesInLdSoConfD;
    }

    /**
     * Sets the value of the createEntriesInLdSoConfD property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setCreateEntriesInLdSoConfD(Boolean value) {
        this.createEntriesInLdSoConfD = value;
    }

    /**
     * Gets the value of the buildClang property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isBuildClang() {
        return buildClang;
    }

    /**
     * Sets the value of the buildClang property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setBuildClang(Boolean value) {
        this.buildClang = value;
    }

    /**
     * Gets the value of the clangTargets property.
     *
     * @return
     *     possible object is
     *     {@link ClangTargetsType }
     *
     */
    public synchronized ClangTargetsType getClangTargets() {
        return clangTargets;
    }

    /**
     * Sets the value of the clangTargets property.
     *
     * @param value
     *     allowed object is
     *     {@link ClangTargetsType }
     *
     */
    public synchronized void setClangTargets(ClangTargetsType value) {
        this.clangTargets = value;
    }

    /**
     * Gets the value of the buildGoogleTest property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isBuildGoogleTest() {
        return buildGoogleTest;
    }

    /**
     * Sets the value of the buildGoogleTest property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setBuildGoogleTest(Boolean value) {
        this.buildGoogleTest = value;
    }

    /**
     * Gets the value of the useSwiftLibDispatch property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isUseSwiftLibDispatch() {
        return useSwiftLibDispatch;
    }

    /**
     * Sets the value of the useSwiftLibDispatch property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setUseSwiftLibDispatch(Boolean value) {
        this.useSwiftLibDispatch = value;
    }

    /**
     * Gets the value of the buildLibDispatchFirst property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isBuildLibDispatchFirst() {
        return buildLibDispatchFirst;
    }

    /**
     * Sets the value of the buildLibDispatchFirst property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setBuildLibDispatchFirst(Boolean value) {
        this.buildLibDispatchFirst = value;
    }

    /**
     * Gets the value of the oldABICompat property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isOldABICompat() {
        return oldABICompat;
    }

    /**
     * Sets the value of the oldABICompat property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setOldABICompat(Boolean value) {
        this.oldABICompat = value;
    }

    /**
     * Gets the value of the customLibName property.
     *
     * @return
     *     possible object is
     *     {@link CustomLibNameType }
     *
     */
    public synchronized CustomLibNameType getCustomLibName() {
        return customLibName;
    }

    /**
     * Sets the value of the customLibName property.
     *
     * @param value
     *     allowed object is
     *     {@link CustomLibNameType }
     *
     */
    public synchronized void setCustomLibName(CustomLibNameType value) {
        this.customLibName = value;
    }

    /**
     * Gets the value of the buildMakeTwice property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isBuildMakeTwice() {
        return buildMakeTwice;
    }

    /**
     * Sets the value of the buildMakeTwice property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setBuildMakeTwice(Boolean value) {
        this.buildMakeTwice = value;
    }

    /**
     * Gets the value of the noMixedABI property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isNoMixedABI() {
        return noMixedABI;
    }

    /**
     * Sets the value of the noMixedABI property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setNoMixedABI(Boolean value) {
        this.noMixedABI = value;
    }

    /**
     * Gets the value of the nonFragileABI property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isNonFragileABI() {
        return nonFragileABI;
    }

    /**
     * Sets the value of the nonFragileABI property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setNonFragileABI(Boolean value) {
        this.nonFragileABI = value;
    }

    /**
     * Gets the value of the objectiveCArc property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isObjectiveCArc() {
        return objectiveCArc;
    }

    /**
     * Sets the value of the objectiveCArc property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setObjectiveCArc(Boolean value) {
        this.objectiveCArc = value;
    }

    /**
     * Gets the value of the debugByDefault property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isDebugByDefault() {
        return debugByDefault;
    }

    /**
     * Sets the value of the debugByDefault property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setDebugByDefault(Boolean value) {
        this.debugByDefault = value;
    }

    /**
     * Gets the value of the nativeObjectiveCExceptions property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public synchronized Boolean isNativeObjectiveCExceptions() {
        return nativeObjectiveCExceptions;
    }

    /**
     * Sets the value of the nativeObjectiveCExceptions property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public synchronized void setNativeObjectiveCExceptions(Boolean value) {
        this.nativeObjectiveCExceptions = value;
    }

    /**
     * Gets the value of the runtimeABI property.
     *
     * @return
     *     possible object is
     *     {@link RuntimeABIEnum }
     *
     */
    public synchronized RuntimeABIEnum getRuntimeABI() {
        return runtimeABI;
    }

    /**
     * Sets the value of the runtimeABI property.
     *
     * @param value
     *     allowed object is
     *     {@link RuntimeABIEnum }
     *
     */
    public synchronized void setRuntimeABI(RuntimeABIEnum value) {
        this.runtimeABI = value;
    }

    /**
     * Gets the value of the libraryCombo property.
     *
     * @return
     *     possible object is
     *     {@link LibraryComboEnum }
     *
     */
    public synchronized LibraryComboEnum getLibraryCombo() {
        return libraryCombo;
    }

    /**
     * Sets the value of the libraryCombo property.
     *
     * @param value
     *     allowed object is
     *     {@link LibraryComboEnum }
     *
     */
    public synchronized void setLibraryCombo(LibraryComboEnum value) {
        this.libraryCombo = value;
    }

    /**
     * Gets the value of the layout property.
     *
     * @return
     *     possible object is
     *     {@link FileSystemLayoutsEnum }
     *
     */
    public synchronized FileSystemLayoutsEnum getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     *
     * @param value
     *     allowed object is
     *     {@link FileSystemLayoutsEnum }
     *
     */
    public synchronized void setLayout(FileSystemLayoutsEnum value) {
        this.layout = value;
    }

    /**
     * Gets the value of the sourceLocations property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceLocations property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceLocations().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceLocation }
     *
     *
     */
    public synchronized List<SourceLocation> getSourceLocations() {
        if (sourceLocations == null) {
            sourceLocations = new ArrayList<SourceLocation>();
        }
        return this.sourceLocations;
    }

}
