//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.18 at 09:54:21 AM EDT
//


package com.galenrhodes.gnustep.builder.options.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.galenrhodes.gnustep.builder.options.data package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GNUstepOptions_QNAME = new QName("http://www.projectgalen.com/gnustepbuilder", "GNUstepOptions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.galenrhodes.gnustep.builder.options.data
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GNUstepOptions }
     *
     */
    public GNUstepOptions createGNUstepOptions() {
        return new GNUstepOptions();
    }

    /**
     * Create an instance of {@link Modules }
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link ClangTargetsType }
     *
     */
    public ClangTargetsType createClangTargetsType() {
        return new ClangTargetsType();
    }

    /**
     * Create an instance of {@link CustomLibNameType }
     *
     */
    public CustomLibNameType createCustomLibNameType() {
        return new CustomLibNameType();
    }

    /**
     * Create an instance of {@link SourceLocation }
     *
     */
    public SourceLocation createSourceLocation() {
        return new SourceLocation();
    }

    /**
     * Create an instance of {@link SourceLocationModule }
     *
     */
    public SourceLocationModule createSourceLocationModule() {
        return new SourceLocationModule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GNUstepOptions }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GNUstepOptions }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.projectgalen.com/gnustepbuilder", name = "GNUstepOptions")
    public JAXBElement<GNUstepOptions> createGNUstepOptions(GNUstepOptions value) {
        return new JAXBElement<GNUstepOptions>(_GNUstepOptions_QNAME, GNUstepOptions.class, null, value);
    }

}
