//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.18 at 12:19:28 PM EDT
//

package com.galenrhodes.gnustep.builder.options.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for PrereqSystemEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrereqSystemEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Debian"/&gt;
 *     &lt;enumeration value="Fedora"/&gt;
 *     &lt;enumeration value="Free-BSD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "PrereqSystemEnum", namespace = "http://www.projectgalen.com/gnustepbuilder")
@XmlEnum
public enum PrereqSystemEnum {

    @XmlEnumValue("Debian") DEBIAN("Debian"), @XmlEnumValue("Fedora") FEDORA("Fedora"), @XmlEnumValue("Free-BSD") FREE_BSD("Free-BSD");
    private final String value;

    PrereqSystemEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrereqSystemEnum fromValue(String v) {
        for(PrereqSystemEnum c : PrereqSystemEnum.values()) {
            if(c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
