//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.18 at 12:19:28 PM EDT
//

package com.galenrhodes.gnustep.builder.options.data;

import javax.xml.bind.annotation.*;

/**
 * <p>Java class for PrereqPackage complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PrereqPackage"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="condition" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrereqPackage", namespace = "http://www.projectgalen.com/gnustepbuilder", propOrder = {
        "value"
})
public class PrereqPackage {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "condition")
    protected String condition;

    /**
     * Gets the value of the condition property.
     *
     * @return possible object is {@link String }
     */
    public synchronized String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     *
     * @param value allowed object is {@link String }
     */
    public synchronized void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is {@link String }
     */
    public synchronized String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is {@link String }
     */
    public synchronized void setValue(String value) {
        this.value = value;
    }

}
