//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.18 at 12:19:28 PM EDT
//

package com.galenrhodes.gnustep.builder.options.data;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for PrereqSystem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PrereqSystem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="System" type="{http://www.projectgalen.com/gnustepbuilder}PrereqSystemEnum"/&gt;
 *         &lt;element name="Packages" type="{http://www.projectgalen.com/gnustepbuilder}PrereqPackage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrereqSystem", namespace = "http://www.projectgalen.com/gnustepbuilder", propOrder = {
        "system", "packages"
})
public class PrereqSystem {

    @XmlElement(name = "System", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true, defaultValue = "Debian")
    @XmlSchemaType(name = "string")
    protected PrereqSystemEnum    system;
    @XmlElement(name = "Packages", namespace = "http://www.projectgalen.com/gnustepbuilder")
    protected List<PrereqPackage> packages;

    /**
     * Gets the value of the packages property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packages property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackages().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link PrereqPackage }
     */
    public synchronized List<PrereqPackage> getPackages() {
        if(packages == null) {
            packages = new ArrayList<PrereqPackage>();
        }
        return this.packages;
    }

    /**
     * Gets the value of the system property.
     *
     * @return possible object is {@link PrereqSystemEnum }
     */
    public synchronized PrereqSystemEnum getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     *
     * @param value allowed object is {@link PrereqSystemEnum }
     */
    public synchronized void setSystem(PrereqSystemEnum value) {
        this.system = value;
    }

}
