//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.18 at 09:54:21 AM EDT
//


package com.galenrhodes.gnustep.builder.options.data;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SourceLocation complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SourceLocation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HostURL" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Modules" type="{http://www.projectgalen.com/gnustepbuilder}SourceLocationModule" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourceLocation", namespace = "http://www.projectgalen.com/gnustepbuilder", propOrder = {
    "name",
    "description",
    "hostURL",
    "type",
    "modules"
})
public class SourceLocation {

    @XmlElement(name = "Name", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected String                     name;
    @XmlElement(name = "Description", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected String                     description;
    @XmlElement(name = "HostURL", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected String                     hostURL;
    @XmlElement(name = "Type", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected String                     type;
    @XmlElement(name = "Modules", namespace = "http://www.projectgalen.com/gnustepbuilder", required = true)
    protected List<SourceLocationModule> modules;
    @XmlAttribute(name = "id", required = true)
    protected String                     id;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public synchronized String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public synchronized void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public synchronized String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public synchronized void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the hostURL property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public synchronized String getHostURL() {
        return hostURL;
    }

    /**
     * Sets the value of the hostURL property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public synchronized void setHostURL(String value) {
        this.hostURL = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public synchronized String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public synchronized void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the modules property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modules property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModules().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceLocationModule }
     *
     *
     */
    public synchronized List<SourceLocationModule> getModules() {
        if (modules == null) {
            modules = new ArrayList<SourceLocationModule>();
        }
        return this.modules;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     */
    public synchronized String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     */
    public synchronized void setId(String value) {
        this.id = value;
    }

}
